
import pytest
from solutions.solution_6 import convert

@pytest.mark.parametrize("s, num_rows, expected", [
    ("PAYPALISHIRING", 3, "PAHNAPLSIIGYIR"),
    ("PAYPALISHIRING", 4, "PINALSIGYAHRPI"),
    ("A", 1, "A"),
    ("ABC", 1, "ABC"),
    ("ABCDE", 4, "ABCED"),
    ("ABCDE", 5, "ABCDE"),
    ("ABCDEF", 2, "ACEBDF"),
    ("ABCDEF", 3, "AEBDFC"),
    ("ABCDEF", 4, "ABECDF"),
    ("ABCDEF", 5, "ABCEDF"),
    ("ABCDEF", 6, "ABCDEF"),
    ("Apalindromeisaword,phrase,number,orothersequenceofunitsthatcanbereadthesamewayineitherdirection,withgeneralallowancesforadjustmentstopunctuationandworddividers.", 10, "A,r,n,w,r,t,a,.,f,e,n,i,d,e,d,c,i,e,w,a,h,o,e,o,s,e,q,u,e,n,c,e,o,f,u,n,i,t,s,t,h,a,t,c,a,n,b,e,r,e,a,d,t,h,e,s,a,m,e,w,a,y,i,n,e,i,t,h,e,r,d,i,r,e,c,t,i,o,n,w,i,t,h,g,e,n,e,r,a,l,a,l,l,o,w,a,n,c,e,s,f,o,r,a,d,j,u,s,t,m,e,n,t,s,t,o,p,u,n,c,t,u,a,t,i,o,n,a,n,d,w,o,r,d,d,i,v,i,d,e,r,s,p,l,a,i,m,o,d"),
    ("a", 2, "a"),
    ("ab", 1, "ab"),
    ("ab", 2, "ab"),
    ("abc", 2, "acb"),
    ("abcd", 2, "acbd"),
    ("abcde", 2, "acebd"),
    ("abcdefg", 3, "aebdfcg"),
    ("abcdefgh", 3, "aeghbfcd"),
    ("abcdefghi", 3, "aegihfbd"),
    ("abcdefghij", 3, "aegijhfbcd"),
    ("abcdefghijk", 3, "aegikhjfbcd"),
    ("abcdefghijkl", 3, "aegikljhfbcd"),
    ("abcdefghijklm", 3, "aegikmjlhfbcd"),
    ("abcdefghijklmn", 3, "aegikmlnjhfbcd"),
    ("abcdefghijklmno", 3, "aegikmolnjhfbcd"),
    ("abcdefghijklmnop", 3, "aegikmolpnjhfbcd"),
    ("abcdefghijklmnopq", 3, "aegikmolpqnjhfbcd"),
    ("abcdefghijklmnopqr", 3, "aegikmolpqrnjhfbcd"),
    ("a", 100, "a"),
    ("", 5, ""),
    ("abcdef", 1, "abcdef"),
    ("abcdef", 7, "abcdef"),
    ("abcdefghijkl", 2, "acegikbdfhjl"),
    ("abcdefghijkl", 4, "agbfhcejidlk"),
    ("abcdefghijkl", 5, "aibjchdkeglf"),
    ("abcdefghijkl", 6, "akbjlicgmdhe"),
    ("abcdefghijkl", 12, "abcdefghijkl"),
    ("abcdefghijkl", 13, "abcdefghijkl"),
    ("a b c d e", 3, "a d bec"),
    ("123456789", 3, "159246837"),
    ("123456789", 4, "172683594"),
    ("123456789", 5, "192837465"),
    ("hello, world!", 3, "h,l!e,o,wrdlo"),
    ("hello, world!", 4, "h o!e,rd,l lwo"),
    ("hello, world!", 5, "h,d!e l,orw lo"),
    ("a b c d e f g", 3, "a e c g b d f"),
    ("a b c d e f g", 4, "a g b f c e d")
])
def test_convert(s, num_rows, expected):
    assert convert(s, num_rows) == expected
